### ISSUE TITLE
testimonials page disappeared 

### ISSUE THREAD

**Issue by dhimmel** [trangdata/zapad#3]
From the build logs of https://github.com/trangdata/zapad/commit/b35d8a2b0fcfb4038e6ee3603963bb26227824c7:

```
[1/2] index.qmd
[2/2] testimonials.qmd
Output created: _site/index.html
```

But the testimonials was not created, so now https://zapad.xyz/testimonials.html gives 404. @trangdata can you look? Maybe quarto changed.

**Comment by trangdata** [comment]
The issue was that the custom domain didn't retain because there were no CNAME file on the [gh-pages](https://github.com/trangdata/zapad/tree/gh-pages) branch. Quarto must have changed this at some point. https://github.com/quarto-dev/quarto-cli/discussions/3249 The Testimonials page is still [there](https://trangdata.github.io/zapad/testimonials.html). You must have had a cache to an old page.

**Comment by dhimmel** [comment]
> The issue was that the custom domain didn't retain because there were no CNAME file on the [gh-pages](https://github.com/trangdata/zapad/tree/gh-pages) branch

Ah makes sense. I think we still a further update beyond https://github.com/trangdata/zapad/commit/b478e1aeff72bf9a86df4a4be183b0e5d4790fc5 to add the source `CNAME` file that will get copied over.

**Comment by trangdata** [comment]
Done in 054856e9d09ab46907a8600068f7969a50c81875.
